### ISSUE TITLE
ability to disable buffering

### ISSUE THREAD

**Issue by marcosrmendezthd** [wavefrontHQ/wavefront-sdk-go#4] opened 2018-12-06 23:24 UTC
Can we add an option to disable buffering metrics that couldn't be sent? We keep that state elsewhere and retry batches of metrics. However if I reuse the client to send another batch of metrics, it'll send whatever it couldn't send last time plus the new metrics, which could be the same metrics.

I suppose a function to clear the buffer could be an option as well. :smile:

**Comment by vikramraman** [comment] 2018-12-07 00:35
@marcosrmendezthd  assume this is for direct ingestion?

**Comment by marcosrmendezthd** [comment] 2018-12-07 00:36
Both senders actually. :D

**Comment by vikramraman** [comment] 2018-12-07 01:32
@marcosrmendezthd The proxy sender doesn't buffer on error like the direct one does. 

It does use a buffered writer: https://github.com/wavefrontHQ/wavefront-sdk-go/blob/5c3555f5bbcb783645aa1e0348c18b763e204646/internal/proxy.go#L20
But doesn't buffer metrics on error: https://github.com/wavefrontHQ/wavefront-sdk-go/blob/5c3555f5bbcb783645aa1e0348c18b763e204646/internal/proxy.go#L119

Shouldn't be hard to add a flag to drop metrics on error for direct ingestion though.

**Comment by prydin** [comment] 2020-09-21 15:19
For some context, refer to this issue. The problem is that the SDK is designed to be "best effort" with minimal blocking time for the caller. This is not desirable when the caller has its own buffer and/or uses senses the throughput of the SDK to apply back pressure. https://github.com/influxdata/telegraf/issues/7409

**Comment by vikramraman** [comment] 2020-09-21 17:25
Main reason we buffer / batch is to maximize network throughput. Works better to batch it up and send points to Wavefront than each point we get. It should be possible to support blocking if the buffer is full rather than drop points (via a flag). Would just need to tweak things here:

https://github.com/wavefrontHQ/wavefront-sdk-go/blob/a9ecf9e538492d362bdd57163c3ad07a565df7de/internal/lines.go#L122

Would that help in addressing this issue on the telegraf side?

**Comment by LukeWinikates** [comment] 2023-02-17 00:45
@oppegard I think this issue is resolved, or some combination of partially resolved and stale. I think it makes sense to close it.

**Comment by oppegard** [comment] 2023-02-17 18:10
Closing. If the current SDK (as of February 2023) still needs a feature in this area, please open a new issue.

**Closed as not planned by oppegard** 2023-02-17 18:10 UTC
